// <auto-generated />
using System;
using Amver.EfCli;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Amver.EfCli.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190416200812_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Amver.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CountryIdId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CountryIdId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Amver.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("TripIdId");

                    b.Property<int?>("UserIdId");

                    b.HasKey("Id");

                    b.HasIndex("TripIdId");

                    b.HasIndex("UserIdId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Amver.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Amver.Domain.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("Amver.Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<int?>("ConversationIdId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("MessageDate");

                    b.Property<int?>("UserOneIdId");

                    b.Property<int?>("UserTwoIdId");

                    b.HasKey("Id");

                    b.HasIndex("ConversationIdId");

                    b.HasIndex("UserOneIdId");

                    b.HasIndex("UserTwoIdId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Amver.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Amver.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateFrom");

                    b.Property<DateTime>("DateTo");

                    b.Property<int?>("FromCityId");

                    b.Property<int?>("FromCountryId");

                    b.Property<int?>("GenderOfCompanionIdId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("RoleIdId");

                    b.Property<int?>("ToCityId");

                    b.Property<int?>("ToCountryId");

                    b.Property<int?>("UserIdId");

                    b.HasKey("Id");

                    b.HasIndex("FromCityId");

                    b.HasIndex("FromCountryId");

                    b.HasIndex("GenderOfCompanionIdId");

                    b.HasIndex("RoleIdId");

                    b.HasIndex("ToCityId");

                    b.HasIndex("ToCountryId");

                    b.HasIndex("UserIdId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Amver.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDay");

                    b.Property<int?>("CityIdId");

                    b.Property<string>("Comment");

                    b.Property<int?>("CountryIdId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<string>("FaceBookId");

                    b.Property<string>("FirstName");

                    b.Property<string>("FullName");

                    b.Property<int?>("GenderIdId");

                    b.Property<bool>("IsBanned");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Photo");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("CityIdId");

                    b.HasIndex("CountryIdId");

                    b.HasIndex("GenderIdId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Amver.Domain.Entities.City", b =>
                {
                    b.HasOne("Amver.Domain.Entities.Country", "CountryId")
                        .WithMany()
                        .HasForeignKey("CountryIdId");
                });

            modelBuilder.Entity("Amver.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Amver.Domain.Entities.Trip", "TripId")
                        .WithMany()
                        .HasForeignKey("TripIdId");

                    b.HasOne("Amver.Domain.Entities.User", "UserId")
                        .WithMany()
                        .HasForeignKey("UserIdId");
                });

            modelBuilder.Entity("Amver.Domain.Entities.Message", b =>
                {
                    b.HasOne("Amver.Domain.Entities.Conversation", "ConversationId")
                        .WithMany()
                        .HasForeignKey("ConversationIdId");

                    b.HasOne("Amver.Domain.Entities.User", "UserOneId")
                        .WithMany()
                        .HasForeignKey("UserOneIdId");

                    b.HasOne("Amver.Domain.Entities.User", "UserTwoId")
                        .WithMany()
                        .HasForeignKey("UserTwoIdId");
                });

            modelBuilder.Entity("Amver.Domain.Entities.Trip", b =>
                {
                    b.HasOne("Amver.Domain.Entities.City", "FromCity")
                        .WithMany()
                        .HasForeignKey("FromCityId");

                    b.HasOne("Amver.Domain.Entities.Country", "FromCountry")
                        .WithMany()
                        .HasForeignKey("FromCountryId");

                    b.HasOne("Amver.Domain.Entities.Gender", "GenderOfCompanionId")
                        .WithMany()
                        .HasForeignKey("GenderOfCompanionIdId");

                    b.HasOne("Amver.Domain.Entities.Role", "RoleId")
                        .WithMany()
                        .HasForeignKey("RoleIdId");

                    b.HasOne("Amver.Domain.Entities.City", "ToCity")
                        .WithMany()
                        .HasForeignKey("ToCityId");

                    b.HasOne("Amver.Domain.Entities.Country", "ToCountry")
                        .WithMany()
                        .HasForeignKey("ToCountryId");

                    b.HasOne("Amver.Domain.Entities.User", "UserId")
                        .WithMany()
                        .HasForeignKey("UserIdId");
                });

            modelBuilder.Entity("Amver.Domain.Entities.User", b =>
                {
                    b.HasOne("Amver.Domain.Entities.City", "CityId")
                        .WithMany()
                        .HasForeignKey("CityIdId");

                    b.HasOne("Amver.Domain.Entities.Country", "CountryId")
                        .WithMany()
                        .HasForeignKey("CountryIdId");

                    b.HasOne("Amver.Domain.Entities.Gender", "GenderId")
                        .WithMany()
                        .HasForeignKey("GenderIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
