//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amver.MobileClient.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Amver.MobileClient.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SearchTab {
            get {
                return ResourceManager.GetString("SearchTab", resourceCulture);
            }
        }
        
        public static string FavouritesTab {
            get {
                return ResourceManager.GetString("FavouritesTab", resourceCulture);
            }
        }
        
        public static string AddTab {
            get {
                return ResourceManager.GetString("AddTab", resourceCulture);
            }
        }
        
        public static string MessagesTab {
            get {
                return ResourceManager.GetString("MessagesTab", resourceCulture);
            }
        }
        
        public static string CabinetTab {
            get {
                return ResourceManager.GetString("CabinetTab", resourceCulture);
            }
        }
        
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        public static string FromCityPlaceholder {
            get {
                return ResourceManager.GetString("FromCityPlaceholder", resourceCulture);
            }
        }
        
        public static string ToCityPlaceholder {
            get {
                return ResourceManager.GetString("ToCityPlaceholder", resourceCulture);
            }
        }
        
        public static string ToCountryPlaceholder {
            get {
                return ResourceManager.GetString("ToCountryPlaceholder", resourceCulture);
            }
        }
        
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        public static string PreferredGender {
            get {
                return ResourceManager.GetString("PreferredGender", resourceCulture);
            }
        }
        
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        public static string CommentPlaceholder {
            get {
                return ResourceManager.GetString("CommentPlaceholder", resourceCulture);
            }
        }
        
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        public static string TravelSuccessfullyAdded {
            get {
                return ResourceManager.GetString("TravelSuccessfullyAdded", resourceCulture);
            }
        }
        
        public static string FromCityIsRequired {
            get {
                return ResourceManager.GetString("FromCityIsRequired", resourceCulture);
            }
        }
        
        public static string ToCityOrToCountryIsRequired {
            get {
                return ResourceManager.GetString("ToCityOrToCountryIsRequired", resourceCulture);
            }
        }
        
        public static string DateToMustBeGreatDateFrom {
            get {
                return ResourceManager.GetString("DateToMustBeGreatDateFrom", resourceCulture);
            }
        }
        
        public static string ToCityFromCityMustBeDifferent {
            get {
                return ResourceManager.GetString("ToCityFromCityMustBeDifferent", resourceCulture);
            }
        }
        
        public static string ToCityToCountryAndToCountryMustBeEqual {
            get {
                return ResourceManager.GetString("ToCityToCountryAndToCountryMustBeEqual", resourceCulture);
            }
        }
        
        public static string GoToTravel {
            get {
                return ResourceManager.GetString("GoToTravel", resourceCulture);
            }
        }
        
        public static string GoToProfile {
            get {
                return ResourceManager.GetString("GoToProfile", resourceCulture);
            }
        }
        
        public static string ToPreposition {
            get {
                return ResourceManager.GetString("ToPreposition", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyLink {
            get {
                return ResourceManager.GetString("PrivacyPolicyLink", resourceCulture);
            }
        }
        
        public static string LicenseLink {
            get {
                return ResourceManager.GetString("LicenseLink", resourceCulture);
            }
        }
        
        public static string LogOutButtonTitle {
            get {
                return ResourceManager.GetString("LogOutButtonTitle", resourceCulture);
            }
        }
        
        public static string LogInButtonTitle {
            get {
                return ResourceManager.GetString("LogInButtonTitle", resourceCulture);
            }
        }
        
        public static string ActiveTravel {
            get {
                return ResourceManager.GetString("ActiveTravel", resourceCulture);
            }
        }
        
        public static string CompletedTravel {
            get {
                return ResourceManager.GetString("CompletedTravel", resourceCulture);
            }
        }
        
        public static string IncompletedTravel {
            get {
                return ResourceManager.GetString("IncompletedTravel", resourceCulture);
            }
        }
        
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        public static string ChatMessagePlaceholder {
            get {
                return ResourceManager.GetString("ChatMessagePlaceholder", resourceCulture);
            }
        }
        
        public static string ChatIsBlockedPlaceholder {
            get {
                return ResourceManager.GetString("ChatIsBlockedPlaceholder", resourceCulture);
            }
        }
        
        public static string QuestionDoYouWantToDeleteTheConversation {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToDeleteTheConversation", resourceCulture);
            }
        }
        
        public static string ConversationSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("ConversationSuccessfullyDeleted", resourceCulture);
            }
        }
        
        public static string SpecifyBirthDayGender {
            get {
                return ResourceManager.GetString("SpecifyBirthDayGender", resourceCulture);
            }
        }
        
        public static string ItCanBeEdited {
            get {
                return ResourceManager.GetString("ItCanBeEdited", resourceCulture);
            }
        }
        
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        public static string NoSpam {
            get {
                return ResourceManager.GetString("NoSpam", resourceCulture);
            }
        }
        
        public static string EmailConfirmLater {
            get {
                return ResourceManager.GetString("EmailConfirmLater", resourceCulture);
            }
        }
        
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string NewToAmver {
            get {
                return ResourceManager.GetString("NewToAmver", resourceCulture);
            }
        }
        
        public static string CreateAnAccount {
            get {
                return ResourceManager.GetString("CreateAnAccount", resourceCulture);
            }
        }
        
        public static string CreateAnAccountClick {
            get {
                return ResourceManager.GetString("CreateAnAccountClick", resourceCulture);
            }
        }
        
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        public static string LoginPlaceholder {
            get {
                return ResourceManager.GetString("LoginPlaceholder", resourceCulture);
            }
        }
        
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string CreatePasswordPlaceholder {
            get {
                return ResourceManager.GetString("CreatePasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyLinkAuth {
            get {
                return ResourceManager.GetString("PrivacyPolicyLinkAuth", resourceCulture);
            }
        }
        
        public static string LicenseLinkAuth {
            get {
                return ResourceManager.GetString("LicenseLinkAuth", resourceCulture);
            }
        }
        
        public static string FieldIsAnEmpty {
            get {
                return ResourceManager.GetString("FieldIsAnEmpty", resourceCulture);
            }
        }
        
        public static string LoginIsNotValid {
            get {
                return ResourceManager.GetString("LoginIsNotValid", resourceCulture);
            }
        }
        
        public static string PasswordIsNotValid {
            get {
                return ResourceManager.GetString("PasswordIsNotValid", resourceCulture);
            }
        }
        
        public static string PasswordsAreNotEqual {
            get {
                return ResourceManager.GetString("PasswordsAreNotEqual", resourceCulture);
            }
        }
        
        public static string EnterYourName {
            get {
                return ResourceManager.GetString("EnterYourName", resourceCulture);
            }
        }
        
        public static string UserNameIsNotValid {
            get {
                return ResourceManager.GetString("UserNameIsNotValid", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string FromCityLocation {
            get {
                return ResourceManager.GetString("FromCityLocation", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        public static string SelectProfileImageButton {
            get {
                return ResourceManager.GetString("SelectProfileImageButton", resourceCulture);
            }
        }
        
        public static string ImageProcessing {
            get {
                return ResourceManager.GetString("ImageProcessing", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        public static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        public static string ConfirmDeleteProfile {
            get {
                return ResourceManager.GetString("ConfirmDeleteProfile", resourceCulture);
            }
        }
        
        public static string ConfirmActionYes {
            get {
                return ResourceManager.GetString("ConfirmActionYes", resourceCulture);
            }
        }
        
        public static string ConfirmActionNo {
            get {
                return ResourceManager.GetString("ConfirmActionNo", resourceCulture);
            }
        }
        
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        public static string NotificationProfileSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("NotificationProfileSuccessfullyDeleted", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string NotificationError {
            get {
                return ResourceManager.GetString("NotificationError", resourceCulture);
            }
        }
        
        public static string NotificationDeviceDoesNotSupportedThisFunction {
            get {
                return ResourceManager.GetString("NotificationDeviceDoesNotSupportedThisFunction", resourceCulture);
            }
        }
        
        public static string NotificationCouldNotGetTheImage {
            get {
                return ResourceManager.GetString("NotificationCouldNotGetTheImage", resourceCulture);
            }
        }
        
        public static string YouHaveBeenBlocked {
            get {
                return ResourceManager.GetString("YouHaveBeenBlocked", resourceCulture);
            }
        }
        
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        public static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        public static string LoginBeforeBlocking {
            get {
                return ResourceManager.GetString("LoginBeforeBlocking", resourceCulture);
            }
        }
        
        public static string UserSuccessfullyBlocked {
            get {
                return ResourceManager.GetString("UserSuccessfullyBlocked", resourceCulture);
            }
        }
        
        public static string UserSuccessfullyUnblocked {
            get {
                return ResourceManager.GetString("UserSuccessfullyUnblocked", resourceCulture);
            }
        }
        
        public static string RegisteredDate {
            get {
                return ResourceManager.GetString("RegisteredDate", resourceCulture);
            }
        }
        
        public static string Eula {
            get {
                return ResourceManager.GetString("Eula", resourceCulture);
            }
        }
        
        public static string IAgreeButton {
            get {
                return ResourceManager.GetString("IAgreeButton", resourceCulture);
            }
        }
        
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        public static string YourReportHasBeenSentSuccessfully {
            get {
                return ResourceManager.GetString("YourReportHasBeenSentSuccessfully", resourceCulture);
            }
        }
        
        public static string CallDoNotWait {
            get {
                return ResourceManager.GetString("CallDoNotWait", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string QuestionDoYouWantToDeleteTheTravel {
            get {
                return ResourceManager.GetString("QuestionDoYouWantToDeleteTheTravel", resourceCulture);
            }
        }
        
        public static string TravelSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("TravelSuccessfullyDeleted", resourceCulture);
            }
        }
        
        public static string QuestionDidTheTravelTakePlace {
            get {
                return ResourceManager.GetString("QuestionDidTheTravelTakePlace", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        public static string IAmFromCity {
            get {
                return ResourceManager.GetString("IAmFromCity", resourceCulture);
            }
        }
        
        public static string CommentPlaceholderProfile {
            get {
                return ResourceManager.GetString("CommentPlaceholderProfile", resourceCulture);
            }
        }
        
        public static string EnterYourCity {
            get {
                return ResourceManager.GetString("EnterYourCity", resourceCulture);
            }
        }
        
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        public static string UserAge {
            get {
                return ResourceManager.GetString("UserAge", resourceCulture);
            }
        }
        
        public static string SendMessageButton {
            get {
                return ResourceManager.GetString("SendMessageButton", resourceCulture);
            }
        }
        
        public static string FromCountryPlaceholder {
            get {
                return ResourceManager.GetString("FromCountryPlaceholder", resourceCulture);
            }
        }
        
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        public static string ToFavorites {
            get {
                return ResourceManager.GetString("ToFavorites", resourceCulture);
            }
        }
        
        public static string InFavorites {
            get {
                return ResourceManager.GetString("InFavorites", resourceCulture);
            }
        }
        
        public static string Travels {
            get {
                return ResourceManager.GetString("Travels", resourceCulture);
            }
        }
        
        public static string SearchNow {
            get {
                return ResourceManager.GetString("SearchNow", resourceCulture);
            }
        }
        
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        public static string TravelSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("TravelSuccessfullyCompleted", resourceCulture);
            }
        }
        
        public static string NudityOrSexualActivity {
            get {
                return ResourceManager.GetString("NudityOrSexualActivity", resourceCulture);
            }
        }
        
        public static string HateSpeechOrSymbols {
            get {
                return ResourceManager.GetString("HateSpeechOrSymbols", resourceCulture);
            }
        }
        
        public static string ViolenceOrDangerousOrganizations {
            get {
                return ResourceManager.GetString("ViolenceOrDangerousOrganizations", resourceCulture);
            }
        }
        
        public static string SaleOfIllegalOrRegularGoods {
            get {
                return ResourceManager.GetString("SaleOfIllegalOrRegularGoods", resourceCulture);
            }
        }
        
        public static string BullyingOrHarassment {
            get {
                return ResourceManager.GetString("BullyingOrHarassment", resourceCulture);
            }
        }
        
        public static string IntellectualPropertyViolation {
            get {
                return ResourceManager.GetString("IntellectualPropertyViolation", resourceCulture);
            }
        }
        
        public static string SuicideOrSelfInjury {
            get {
                return ResourceManager.GetString("SuicideOrSelfInjury", resourceCulture);
            }
        }
        
        public static string ScamOrFraud {
            get {
                return ResourceManager.GetString("ScamOrFraud", resourceCulture);
            }
        }
        
        public static string FalseInformation {
            get {
                return ResourceManager.GetString("FalseInformation", resourceCulture);
            }
        }
        
        public static string FavoriteTravels {
            get {
                return ResourceManager.GetString("FavoriteTravels", resourceCulture);
            }
        }
        
        public static string MyTravels {
            get {
                return ResourceManager.GetString("MyTravels", resourceCulture);
            }
        }
        
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        public static string AgeConstraint {
            get {
                return ResourceManager.GetString("AgeConstraint", resourceCulture);
            }
        }
        
        public static string SetProfilePhoto {
            get {
                return ResourceManager.GetString("SetProfilePhoto", resourceCulture);
            }
        }
    }
}
