//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amver.Api.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Amver.Api.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UserIsDeletedOrBanned {
            get {
                return ResourceManager.GetString("UserIsDeletedOrBanned", resourceCulture);
            }
        }
        
        internal static string PasswordOrLoginIsWrong {
            get {
                return ResourceManager.GetString("PasswordOrLoginIsWrong", resourceCulture);
            }
        }
        
        internal static string LoginIsNotValid {
            get {
                return ResourceManager.GetString("LoginIsNotValid", resourceCulture);
            }
        }
        
        internal static string PasswordIsNotValid {
            get {
                return ResourceManager.GetString("PasswordIsNotValid", resourceCulture);
            }
        }
        
        internal static string TripsCountConstraint {
            get {
                return ResourceManager.GetString("TripsCountConstraint", resourceCulture);
            }
        }
    }
}
